name: main

on:
  push:
    branches:
      - versions
  pull_request:
    branches:
      - versions

jobs
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install t ox
      - name: run tox
        run: tox